#ifndef NH_DOM_COMMENT_H
#define NH_DOM_COMMENT_H

#ifndef DOXYGEN_SHOULD_SKIP_THIS

/**
 * Netzhaut - Web Browser Engine
 * Copyright (C) 2020  Dajo Frey
 * Published under LGPLv3
 *
 * This file was generated by NhInstaller
 */

#endif

/** @addtogroup NhFunctions Functions
 *  @{
 */

    Nh_WebIDL_Result Nh_DOM_Comment_constructor(
        Nh_WebIDL_Object *This_p, Nh_List Arguments
    );

/** @} */

#endif