#ifndef NH_DOM_ELEMENT_H
#define NH_DOM_ELEMENT_H

#ifndef DOXYGEN_SHOULD_SKIP_THIS

/**
 * Netzhaut - Web Browser Engine
 * Copyright (C) 2020  Dajo Frey
 * Published under LGPLv3
 *
 * This file was generated by NhInstaller
 */

#endif

/** @addtogroup NhFunctions Functions
 *  @{
 */

    Nh_WebIDL_Result Nh_DOM_Element_hasAttributes(
        Nh_WebIDL_Object *This_p, Nh_List Arguments
    );

    Nh_WebIDL_Result Nh_DOM_Element_getAttributeNames(
        Nh_WebIDL_Object *This_p, Nh_List Arguments
    );

    Nh_WebIDL_Result Nh_DOM_Element_getAttribute(
        Nh_WebIDL_Object *This_p, Nh_List Arguments
    );

    Nh_WebIDL_Result Nh_DOM_Element_getAttributeNS(
        Nh_WebIDL_Object *This_p, Nh_List Arguments
    );

    Nh_WebIDL_Result Nh_DOM_Element_setAttribute(
        Nh_WebIDL_Object *This_p, Nh_List Arguments
    );

    Nh_WebIDL_Result Nh_DOM_Element_setAttributeNS(
        Nh_WebIDL_Object *This_p, Nh_List Arguments
    );

    Nh_WebIDL_Result Nh_DOM_Element_removeAttribute(
        Nh_WebIDL_Object *This_p, Nh_List Arguments
    );

    Nh_WebIDL_Result Nh_DOM_Element_removeAttributeNS(
        Nh_WebIDL_Object *This_p, Nh_List Arguments
    );

    Nh_WebIDL_Result Nh_DOM_Element_toggleAttribute(
        Nh_WebIDL_Object *This_p, Nh_List Arguments
    );

    Nh_WebIDL_Result Nh_DOM_Element_hasAttribute(
        Nh_WebIDL_Object *This_p, Nh_List Arguments
    );

    Nh_WebIDL_Result Nh_DOM_Element_hasAttributeNS(
        Nh_WebIDL_Object *This_p, Nh_List Arguments
    );

    Nh_WebIDL_Result Nh_DOM_Element_getAttributeNode(
        Nh_WebIDL_Object *This_p, Nh_List Arguments
    );

    Nh_WebIDL_Result Nh_DOM_Element_getAttributeNodeNS(
        Nh_WebIDL_Object *This_p, Nh_List Arguments
    );

    Nh_WebIDL_Result Nh_DOM_Element_setAttributeNode(
        Nh_WebIDL_Object *This_p, Nh_List Arguments
    );

    Nh_WebIDL_Result Nh_DOM_Element_setAttributeNodeNS(
        Nh_WebIDL_Object *This_p, Nh_List Arguments
    );

    Nh_WebIDL_Result Nh_DOM_Element_removeAttributeNode(
        Nh_WebIDL_Object *This_p, Nh_List Arguments
    );

    Nh_WebIDL_Result Nh_DOM_Element_attachShadow(
        Nh_WebIDL_Object *This_p, Nh_List Arguments
    );

    Nh_WebIDL_Result Nh_DOM_Element_closest(
        Nh_WebIDL_Object *This_p, Nh_List Arguments
    );

    Nh_WebIDL_Result Nh_DOM_Element_matches(
        Nh_WebIDL_Object *This_p, Nh_List Arguments
    );

    Nh_WebIDL_Result Nh_DOM_Element_webkitMatchesSelector(
        Nh_WebIDL_Object *This_p, Nh_List Arguments
    );

    Nh_WebIDL_Result Nh_DOM_Element_getElementsByTagName(
        Nh_WebIDL_Object *This_p, Nh_List Arguments
    );

    Nh_WebIDL_Result Nh_DOM_Element_getElementsByTagNameNS(
        Nh_WebIDL_Object *This_p, Nh_List Arguments
    );

    Nh_WebIDL_Result Nh_DOM_Element_getElementsByClassName(
        Nh_WebIDL_Object *This_p, Nh_List Arguments
    );

    Nh_WebIDL_Result Nh_DOM_Element_insertAdjacentElement(
        Nh_WebIDL_Object *This_p, Nh_List Arguments
    );

    Nh_WebIDL_Result Nh_DOM_Element_insertAdjacentText(
        Nh_WebIDL_Object *This_p, Nh_List Arguments
    );

/** @} */

#endif