#ifndef NH_DOM_EVENTTARGET_H
#define NH_DOM_EVENTTARGET_H

#ifndef DOXYGEN_SHOULD_SKIP_THIS

/**
 * Netzhaut - Web Browser Engine
 * Copyright (C) 2020  Dajo Frey
 * Published under LGPLv3
 *
 * This file was generated by NhWebIDLSerializer
 */

#endif

/** @addtogroup NhFunctions Functions
 *  @{
 */

    Nh_WebIDL_Result Nh_DOM_EventTarget_constructor(
        Nh_WebIDL_Object *This_p, Nh_List Arguments
    );

    Nh_WebIDL_Result Nh_DOM_EventTarget_addEventListener(
        Nh_WebIDL_Object *This_p, Nh_List Arguments
    );

    Nh_WebIDL_Result Nh_DOM_EventTarget_removeEventListener(
        Nh_WebIDL_Object *This_p, Nh_List Arguments
    );

    Nh_WebIDL_Result Nh_DOM_EventTarget_dispatchEvent(
        Nh_WebIDL_Object *This_p, Nh_List Arguments
    );

/** @} */

#endif