#ifndef NH_DOM_PARENTNODE_H
#define NH_DOM_PARENTNODE_H

#ifndef DOXYGEN_SHOULD_SKIP_THIS

/**
 * Netzhaut - Web Browser Engine
 * Copyright (C) 2020  Dajo Frey
 * Published under LGPLv3
 *
 * This file was generated by NhInstaller
 */

#endif

/** @addtogroup NhFunctions Functions
 *  @{
 */

    Nh_WebIDL_Result Nh_DOM_ParentNode_prepend(
        Nh_WebIDL_Object *This_p, Nh_List Arguments
    );

    Nh_WebIDL_Result Nh_DOM_ParentNode_append(
        Nh_WebIDL_Object *This_p, Nh_List Arguments
    );

    Nh_WebIDL_Result Nh_DOM_ParentNode_replaceChildren(
        Nh_WebIDL_Object *This_p, Nh_List Arguments
    );

    Nh_WebIDL_Result Nh_DOM_ParentNode_querySelector(
        Nh_WebIDL_Object *This_p, Nh_List Arguments
    );

    Nh_WebIDL_Result Nh_DOM_ParentNode_querySelectorAll(
        Nh_WebIDL_Object *This_p, Nh_List Arguments
    );

/** @} */

#endif