#ifndef NH_DOM_TREEWALKER_H
#define NH_DOM_TREEWALKER_H

#ifndef DOXYGEN_SHOULD_SKIP_THIS

/**
 * Netzhaut - Web Browser Engine
 * Copyright (C) 2020  Dajo Frey
 * Published under LGPLv3
 *
 * This file was generated by NhWebIDLSerializer
 */

#endif

/** @addtogroup NhFunctions Functions
 *  @{
 */

    Nh_WebIDL_Result Nh_DOM_TreeWalker_parentNode(
        Nh_WebIDL_Object *This_p, Nh_List Arguments
    );

    Nh_WebIDL_Result Nh_DOM_TreeWalker_firstChild(
        Nh_WebIDL_Object *This_p, Nh_List Arguments
    );

    Nh_WebIDL_Result Nh_DOM_TreeWalker_lastChild(
        Nh_WebIDL_Object *This_p, Nh_List Arguments
    );

    Nh_WebIDL_Result Nh_DOM_TreeWalker_previousSibling(
        Nh_WebIDL_Object *This_p, Nh_List Arguments
    );

    Nh_WebIDL_Result Nh_DOM_TreeWalker_nextSibling(
        Nh_WebIDL_Object *This_p, Nh_List Arguments
    );

    Nh_WebIDL_Result Nh_DOM_TreeWalker_previousNode(
        Nh_WebIDL_Object *This_p, Nh_List Arguments
    );

    Nh_WebIDL_Result Nh_DOM_TreeWalker_nextNode(
        Nh_WebIDL_Object *This_p, Nh_List Arguments
    );

/** @} */

#endif