#ifndef NH_ENCODING_UNICODE_DATA_H
#define NH_ENCODING_UNICODE_DATA_H

#ifndef DOXYGEN_SHOULD_SKIP_THIS

/**
 * Netzhaut - Web Browser Engine
 * Copyright (C) 2022  Dajo Frey
 * Published under GNU LGPL. See Netzhaut/LICENSE.LGPL file.
 *
 * This file was generated by nhmake
 */

#include "../Common/Includes.h"

#endif

/** @addtogroup lib_nhcore_macros
 *  @{
 */

    #define NH_ENCODING_UNICODE_DATA_COUNT 34279
    #define NH_ENCODING_UNICODE_DATA_UNDEFINED_RANGES_COUNT 693

/** @} */

/** @addtogroup lib_nhcore_vars
 *  @{
 */

    extern const NH_BYTE NH_ENCODING_UNICODE_DATA_PP[34279][255];
    extern const long NH_ENCODING_UNICODE_DATA_UNDEFINED_RANGES_PP[693][2];

/** @} */

#endif