#ifndef NH_CSS_COLOR_H
#define NH_CSS_COLOR_H

#ifndef DOXYGEN_SHOULD_SKIP_THIS

/**
 * Netzhaut - Web Browser Engine
 * Copyright (C) 2020  Dajo Frey
 * Published under LGPLv3
 */

#include <stddef.h>

#include "../../API/Header/Netzhaut.h"

#endif

/** @addtogroup CSSData Data
 *  \ingroup CSS
 *  @{
 */

    extern const char *NH_CSS_COLORS_PP[];
    extern size_t NH_CSS_COLORS_PP_COUNT;

/** @} */

/** @addtogroup CSSEnums Enums
 *  \ingroup CSS
 *  @{
 */

    typedef enum NH_CSS_COLOR_NAME {
        NH_CSS_COLOR_NAME_ALICE_BLUE, 	
        NH_CSS_COLOR_NAME_ANTIQUE_WHITE,  	
        NH_CSS_COLOR_NAME_AQUA, 
        NH_CSS_COLOR_NAME_AQUAMARINE,
        NH_CSS_COLOR_NAME_AZURE,	
        NH_CSS_COLOR_NAME_BEIGE,	
        NH_CSS_COLOR_NAME_BISQUE, 	
        NH_CSS_COLOR_NAME_BLACK,	
        NH_CSS_COLOR_NAME_BLANCHED_ALMOND,
        NH_CSS_COLOR_NAME_BLUE,
        NH_CSS_COLOR_NAME_BLUE_VIOLET, 	
        NH_CSS_COLOR_NAME_BROWN,	
        NH_CSS_COLOR_NAME_BURLY_WOOD,  	
        NH_CSS_COLOR_NAME_CADET_BLUE,	
        NH_CSS_COLOR_NAME_CHARTREUSE, 	
        NH_CSS_COLOR_NAME_CHOCOLATE,	
        NH_CSS_COLOR_NAME_CORAL,	
        NH_CSS_COLOR_NAME_CORNFLOWER_BLUE, 
        NH_CSS_COLOR_NAME_CORNSILK,	
        NH_CSS_COLOR_NAME_CRIMSON,	
        NH_CSS_COLOR_NAME_CYAN,
        NH_CSS_COLOR_NAME_DARK_BLUE,
        NH_CSS_COLOR_NAME_DARK_CYAN,	
        NH_CSS_COLOR_NAME_DARK_GOLDEN_ROD,
        NH_CSS_COLOR_NAME_DARK_GRAY,
        NH_CSS_COLOR_NAME_DARK_GREY,	
        NH_CSS_COLOR_NAME_DARK_GREEN, 	
        NH_CSS_COLOR_NAME_DARK_KHAKI,	
        NH_CSS_COLOR_NAME_DARK_MAGENTA,  	
        NH_CSS_COLOR_NAME_DARK_OLIVE_GREEN, 
        NH_CSS_COLOR_NAME_DARK_ORANGE,
        NH_CSS_COLOR_NAME_DARK_ORCHID,	
        NH_CSS_COLOR_NAME_DARK_RED,	
        NH_CSS_COLOR_NAME_DARK_SALMON,  	
        NH_CSS_COLOR_NAME_DARK_SEA_GREEN, 	
        NH_CSS_COLOR_NAME_DARK_SLATE_BLUE, 
        NH_CSS_COLOR_NAME_DARK_SLATE_GRAY,  
        NH_CSS_COLOR_NAME_DARK_SLATE_GREY,  
        NH_CSS_COLOR_NAME_DARK_TURQUOISE,  
        NH_CSS_COLOR_NAME_DARK_VIOLET,  	
        NH_CSS_COLOR_NAME_DEEP_PINK,	
        NH_CSS_COLOR_NAME_DEEP_SKY_BLUE,  	
        NH_CSS_COLOR_NAME_DIM_GRAY,	
        NH_CSS_COLOR_NAME_DIM_GREY,	
        NH_CSS_COLOR_NAME_DODGER_BLUE, 	
        NH_CSS_COLOR_NAME_FIRE_BRICK,	
        NH_CSS_COLOR_NAME_FLORAL_WHITE,  	
        NH_CSS_COLOR_NAME_FOREST_GREEN,	
        NH_CSS_COLOR_NAME_FUCHSIA,	
        NH_CSS_COLOR_NAME_GAINSBORO,  	
        NH_CSS_COLOR_NAME_GHOST_WHITE, 	
        NH_CSS_COLOR_NAME_GOLD,
        NH_CSS_COLOR_NAME_GOLDEN_ROD,
        NH_CSS_COLOR_NAME_GRAY,
        NH_CSS_COLOR_NAME_GREY,	 
        NH_CSS_COLOR_NAME_GREEN, 	
        NH_CSS_COLOR_NAME_GREEN_YELLOW, 	
        NH_CSS_COLOR_NAME_HONEY_DEW,	
        NH_CSS_COLOR_NAME_HOT_PINK,	
        NH_CSS_COLOR_NAME_INDIAN_RED,   	
        NH_CSS_COLOR_NAME_INDIGO,	
        NH_CSS_COLOR_NAME_IVORY,	
        NH_CSS_COLOR_NAME_KHAKI,	
        NH_CSS_COLOR_NAME_LAVENDER,  	
        NH_CSS_COLOR_NAME_LAVENDER_BLUSH,
        NH_CSS_COLOR_NAME_LAWN_GREEN,
        NH_CSS_COLOR_NAME_LEMON_CHIFFON,  	
        NH_CSS_COLOR_NAME_LIGHT_BLUE,	
        NH_CSS_COLOR_NAME_LIGHT_CORAL, 	
        NH_CSS_COLOR_NAME_LIGHT_CYAN,	
        NH_CSS_COLOR_NAME_LIGHT_GOLDEN_ROD,
        NH_CSS_COLOR_NAME_LIGHT_GRAY,
        NH_CSS_COLOR_NAME_LIGHT_GREY,	
        NH_CSS_COLOR_NAME_LIGHT_GREEN, 	
        NH_CSS_COLOR_NAME_LIGHT_PINK,	
        NH_CSS_COLOR_NAME_LIGHT_SALMON,  	
        NH_CSS_COLOR_NAME_LIGHT_SEA_GREEN,
        NH_CSS_COLOR_NAME_LIGHT_SKY_BLUE,
        NH_CSS_COLOR_NAME_LIGHT_SLATE_GRAY, 
        NH_CSS_COLOR_NAME_LIGHT_SLATE_GREY,
        NH_CSS_COLOR_NAME_LIGHT_STEEL_BLUE,
        NH_CSS_COLOR_NAME_LIGHT_YELLOW,
        NH_CSS_COLOR_NAME_LIME,
        NH_CSS_COLOR_NAME_LIME_GREEN,	
        NH_CSS_COLOR_NAME_LINEN,	
        NH_CSS_COLOR_NAME_MAGENTA,  	
        NH_CSS_COLOR_NAME_MAROON,	
        NH_CSS_COLOR_NAME_MEDIUM_AQUAMARINE,
        NH_CSS_COLOR_NAME_MEDIUM_BLUE,
        NH_CSS_COLOR_NAME_MEDIUM_ORCHID,  	
        NH_CSS_COLOR_NAME_MEDIUM_PURPLE,	
        NH_CSS_COLOR_NAME_MEDIUM_SEA_GREEN, 	
        NH_CSS_COLOR_NAME_MEDIUM_SLATE_BLUE,	
        NH_CSS_COLOR_NAME_MEDIUM_SPRING_GREEN,	
        NH_CSS_COLOR_NAME_MEDIUM_TURQUOISE,	
        NH_CSS_COLOR_NAME_MEDIUM_VIOLET_RED,	
        NH_CSS_COLOR_NAME_MIDNIGHT_BLUE,
        NH_CSS_COLOR_NAME_MINT_CREAM,	
        NH_CSS_COLOR_NAME_MISTY_ROSE,	
        NH_CSS_COLOR_NAME_MOCCASIN,	
        NH_CSS_COLOR_NAME_NAVAJO_WHITE,  	
        NH_CSS_COLOR_NAME_NAVY,
        NH_CSS_COLOR_NAME_OLD_LACE,  	
        NH_CSS_COLOR_NAME_OLIVE,	
        NH_CSS_COLOR_NAME_OLIVE_DRAB,  	
        NH_CSS_COLOR_NAME_ORANGE,	
        NH_CSS_COLOR_NAME_ORANGE_RED,  	
        NH_CSS_COLOR_NAME_ORCHID,	
        NH_CSS_COLOR_NAME_PALE_GOLDEN_ROD,  
        NH_CSS_COLOR_NAME_PALE_GREEN,
        NH_CSS_COLOR_NAME_PALE_TURQUOISE,  
        NH_CSS_COLOR_NAME_PALE_VIOLET_RED,
        NH_CSS_COLOR_NAME_PAPAYA_WHIP,
        NH_CSS_COLOR_NAME_PEACH_PUFF,	
        NH_CSS_COLOR_NAME_PERU,
        NH_CSS_COLOR_NAME_PINK,
        NH_CSS_COLOR_NAME_PLUM,
        NH_CSS_COLOR_NAME_POWDER_BLUE,  	
        NH_CSS_COLOR_NAME_PURPLE,	
        NH_CSS_COLOR_NAME_REBECCA_PURPLE,  
        NH_CSS_COLOR_NAME_RED,
        NH_CSS_COLOR_NAME_ROSY_BROWN,
        NH_CSS_COLOR_NAME_ROYAL_BLUE,	
        NH_CSS_COLOR_NAME_SADDLE_BROWN, 	
        NH_CSS_COLOR_NAME_SALMON,	
        NH_CSS_COLOR_NAME_SANDY_BROWN,	
        NH_CSS_COLOR_NAME_SEA_GREEN,	
        NH_CSS_COLOR_NAME_SEA_SHELL,	
        NH_CSS_COLOR_NAME_SIENNA,	
        NH_CSS_COLOR_NAME_SILVER,	
        NH_CSS_COLOR_NAME_SKY_BLUE, 	
        NH_CSS_COLOR_NAME_SLATE_BLUE,  	
        NH_CSS_COLOR_NAME_SLATE_GRAY,	
        NH_CSS_COLOR_NAME_SLATE_GREY,	
        NH_CSS_COLOR_NAME_SNOW,
        NH_CSS_COLOR_NAME_SPRING_GREEN,
        NH_CSS_COLOR_NAME_STEEL_BLUE,	
        NH_CSS_COLOR_NAME_TAN,
        NH_CSS_COLOR_NAME_TEAL,
        NH_CSS_COLOR_NAME_THISTLE,  	
        NH_CSS_COLOR_NAME_TOMATO,	
        NH_CSS_COLOR_NAME_TURQUOISE,  	
        NH_CSS_COLOR_NAME_VIOLET,	
        NH_CSS_COLOR_NAME_WHEAT,	
        NH_CSS_COLOR_NAME_WHITE,	
        NH_CSS_COLOR_NAME_WHITE_SMOKE,  	
        NH_CSS_COLOR_NAME_YELLOW,	
        NH_CSS_COLOR_NAME_YELLOW_GREEN,  
    } NH_CSS_COLOR_NAME;

/** @} */

/** @addtogroup CSSFunctions Functions
 *  \ingroup CSS
 *  @{
 */

    /**
     * Converts a string with hex color syntax to float values.
     * A hexadecimal color is specified with: #RRGGBB, where the RR (red), GG (green) and BB 
     * (blue) hexadecimal integers specify the components of the color. All values must be 
     * between 00 and FF.
     */ 
    void Nh_CSS_parseHexColor(
        char *str_p, float rgba_p[4]
    );

    void Nh_CSS_getColor(
        char *color_p, float values_p[4]
    );

/** @} */

#endif 
