#ifndef NH_CSS_DATA_H
#define NH_CSS_DATA_H

#ifndef DOXYGEN_SHOULD_SKIP_THIS

/**
 * Netzhaut - Web Browser Engine
 * Copyright (C) 2020  Dajo Frey
 * Published under LGPLv3
 */

#include <stddef.h>

#include "../../API/Header/Netzhaut.h"

#endif

/** @addtogroup CSSEnums Enums
 *  \ingroup CSS
 *  @{
 */

    typedef enum NH_CSS_COLOR_NAME {
        NH_CSS_COLOR_NAME_ALICE_BLUE, 	
        NH_CSS_COLOR_NAME_ANTIQUE_WHITE,  	
        NH_CSS_COLOR_NAME_AQUA, 
        NH_CSS_COLOR_NAME_AQUAMARINE,
        NH_CSS_COLOR_NAME_AZURE,	
        NH_CSS_COLOR_NAME_BEIGE,	
        NH_CSS_COLOR_NAME_BISQUE, 	
        NH_CSS_COLOR_NAME_BLACK,	
        NH_CSS_COLOR_NAME_BLANCHED_ALMOND,
        NH_CSS_COLOR_NAME_BLUE,
        NH_CSS_COLOR_NAME_BLUE_VIOLET, 	
        NH_CSS_COLOR_NAME_BROWN,	
        NH_CSS_COLOR_NAME_BURLY_WOOD,  	
        NH_CSS_COLOR_NAME_CADET_BLUE,	
        NH_CSS_COLOR_NAME_CHARTREUSE, 	
        NH_CSS_COLOR_NAME_CHOCOLATE,	
        NH_CSS_COLOR_NAME_CORAL,	
        NH_CSS_COLOR_NAME_CORNFLOWER_BLUE, 
        NH_CSS_COLOR_NAME_CORNSILK,	
        NH_CSS_COLOR_NAME_CRIMSON,	
        NH_CSS_COLOR_NAME_CYAN,
        NH_CSS_COLOR_NAME_DARK_BLUE,
        NH_CSS_COLOR_NAME_DARK_CYAN,	
        NH_CSS_COLOR_NAME_DARK_GOLDEN_ROD,
        NH_CSS_COLOR_NAME_DARK_GRAY,
        NH_CSS_COLOR_NAME_DARK_GREY,	
        NH_CSS_COLOR_NAME_DARK_GREEN, 	
        NH_CSS_COLOR_NAME_DARK_KHAKI,	
        NH_CSS_COLOR_NAME_DARK_MAGENTA,  	
        NH_CSS_COLOR_NAME_DARK_OLIVE_GREEN, 
        NH_CSS_COLOR_NAME_DARK_ORANGE,
        NH_CSS_COLOR_NAME_DARK_ORCHID,	
        NH_CSS_COLOR_NAME_DARK_RED,	
        NH_CSS_COLOR_NAME_DARK_SALMON,  	
        NH_CSS_COLOR_NAME_DARK_SEA_GREEN, 	
        NH_CSS_COLOR_NAME_DARK_SLATE_BLUE, 
        NH_CSS_COLOR_NAME_DARK_SLATE_GRAY,  
        NH_CSS_COLOR_NAME_DARK_SLATE_GREY,  
        NH_CSS_COLOR_NAME_DARK_TURQUOISE,  
        NH_CSS_COLOR_NAME_DARK_VIOLET,  	
        NH_CSS_COLOR_NAME_DEEP_PINK,	
        NH_CSS_COLOR_NAME_DEEP_SKY_BLUE,  	
        NH_CSS_COLOR_NAME_DIM_GRAY,	
        NH_CSS_COLOR_NAME_DIM_GREY,	
        NH_CSS_COLOR_NAME_DODGER_BLUE, 	
        NH_CSS_COLOR_NAME_FIRE_BRICK,	
        NH_CSS_COLOR_NAME_FLORAL_WHITE,  	
        NH_CSS_COLOR_NAME_FOREST_GREEN,	
        NH_CSS_COLOR_NAME_FUCHSIA,	
        NH_CSS_COLOR_NAME_GAINSBORO,  	
        NH_CSS_COLOR_NAME_GHOST_WHITE, 	
        NH_CSS_COLOR_NAME_GOLD,
        NH_CSS_COLOR_NAME_GOLDEN_ROD,
        NH_CSS_COLOR_NAME_GRAY,
        NH_CSS_COLOR_NAME_GREY,	 
        NH_CSS_COLOR_NAME_GREEN, 	
        NH_CSS_COLOR_NAME_GREEN_YELLOW, 	
        NH_CSS_COLOR_NAME_HONEY_DEW,	
        NH_CSS_COLOR_NAME_HOT_PINK,	
        NH_CSS_COLOR_NAME_INDIAN_RED,   	
        NH_CSS_COLOR_NAME_INDIGO,	
        NH_CSS_COLOR_NAME_IVORY,	
        NH_CSS_COLOR_NAME_KHAKI,	
        NH_CSS_COLOR_NAME_LAVENDER,  	
        NH_CSS_COLOR_NAME_LAVENDER_BLUSH,
        NH_CSS_COLOR_NAME_LAWN_GREEN,
        NH_CSS_COLOR_NAME_LEMON_CHIFFON,  	
        NH_CSS_COLOR_NAME_LIGHT_BLUE,	
        NH_CSS_COLOR_NAME_LIGHT_CORAL, 	
        NH_CSS_COLOR_NAME_LIGHT_CYAN,	
        NH_CSS_COLOR_NAME_LIGHT_GOLDEN_ROD,
        NH_CSS_COLOR_NAME_LIGHT_GRAY,
        NH_CSS_COLOR_NAME_LIGHT_GREY,	
        NH_CSS_COLOR_NAME_LIGHT_GREEN, 	
        NH_CSS_COLOR_NAME_LIGHT_PINK,	
        NH_CSS_COLOR_NAME_LIGHT_SALMON,  	
        NH_CSS_COLOR_NAME_LIGHT_SEA_GREEN,
        NH_CSS_COLOR_NAME_LIGHT_SKY_BLUE,
        NH_CSS_COLOR_NAME_LIGHT_SLATE_GRAY, 
        NH_CSS_COLOR_NAME_LIGHT_SLATE_GREY,
        NH_CSS_COLOR_NAME_LIGHT_STEEL_BLUE,
        NH_CSS_COLOR_NAME_LIGHT_YELLOW,
        NH_CSS_COLOR_NAME_LIME,
        NH_CSS_COLOR_NAME_LIME_GREEN,	
        NH_CSS_COLOR_NAME_LINEN,	
        NH_CSS_COLOR_NAME_MAGENTA,  	
        NH_CSS_COLOR_NAME_MAROON,	
        NH_CSS_COLOR_NAME_MEDIUM_AQUAMARINE,
        NH_CSS_COLOR_NAME_MEDIUM_BLUE,
        NH_CSS_COLOR_NAME_MEDIUM_ORCHID,  	
        NH_CSS_COLOR_NAME_MEDIUM_PURPLE,	
        NH_CSS_COLOR_NAME_MEDIUM_SEA_GREEN, 	
        NH_CSS_COLOR_NAME_MEDIUM_SLATE_BLUE,	
        NH_CSS_COLOR_NAME_MEDIUM_SPRING_GREEN,	
        NH_CSS_COLOR_NAME_MEDIUM_TURQUOISE,	
        NH_CSS_COLOR_NAME_MEDIUM_VIOLET_RED,	
        NH_CSS_COLOR_NAME_MIDNIGHT_BLUE,
        NH_CSS_COLOR_NAME_MINT_CREAM,	
        NH_CSS_COLOR_NAME_MISTY_ROSE,	
        NH_CSS_COLOR_NAME_MOCCASIN,	
        NH_CSS_COLOR_NAME_NAVAJO_WHITE,  	
        NH_CSS_COLOR_NAME_NAVY,
        NH_CSS_COLOR_NAME_OLD_LACE,  	
        NH_CSS_COLOR_NAME_OLIVE,	
        NH_CSS_COLOR_NAME_OLIVE_DRAB,  	
        NH_CSS_COLOR_NAME_ORANGE,	
        NH_CSS_COLOR_NAME_ORANGE_RED,  	
        NH_CSS_COLOR_NAME_ORCHID,	
        NH_CSS_COLOR_NAME_PALE_GOLDEN_ROD,  
        NH_CSS_COLOR_NAME_PALE_GREEN,
        NH_CSS_COLOR_NAME_PALE_TURQUOISE,  
        NH_CSS_COLOR_NAME_PALE_VIOLET_RED,
        NH_CSS_COLOR_NAME_PAPAYA_WHIP,
        NH_CSS_COLOR_NAME_PEACH_PUFF,	
        NH_CSS_COLOR_NAME_PERU,
        NH_CSS_COLOR_NAME_PINK,
        NH_CSS_COLOR_NAME_PLUM,
        NH_CSS_COLOR_NAME_POWDER_BLUE,  	
        NH_CSS_COLOR_NAME_PURPLE,	
        NH_CSS_COLOR_NAME_REBECCA_PURPLE,  
        NH_CSS_COLOR_NAME_RED,
        NH_CSS_COLOR_NAME_ROSY_BROWN,
        NH_CSS_COLOR_NAME_ROYAL_BLUE,	
        NH_CSS_COLOR_NAME_SADDLE_BROWN, 	
        NH_CSS_COLOR_NAME_SALMON,	
        NH_CSS_COLOR_NAME_SANDY_BROWN,	
        NH_CSS_COLOR_NAME_SEA_GREEN,	
        NH_CSS_COLOR_NAME_SEA_SHELL,	
        NH_CSS_COLOR_NAME_SIENNA,	
        NH_CSS_COLOR_NAME_SILVER,	
        NH_CSS_COLOR_NAME_SKY_BLUE, 	
        NH_CSS_COLOR_NAME_SLATE_BLUE,  	
        NH_CSS_COLOR_NAME_SLATE_GRAY,	
        NH_CSS_COLOR_NAME_SLATE_GREY,	
        NH_CSS_COLOR_NAME_SNOW,
        NH_CSS_COLOR_NAME_SPRING_GREEN,
        NH_CSS_COLOR_NAME_STEEL_BLUE,	
        NH_CSS_COLOR_NAME_TAN,
        NH_CSS_COLOR_NAME_TEAL,
        NH_CSS_COLOR_NAME_THISTLE,  	
        NH_CSS_COLOR_NAME_TOMATO,	
        NH_CSS_COLOR_NAME_TURQUOISE,  	
        NH_CSS_COLOR_NAME_VIOLET,	
        NH_CSS_COLOR_NAME_WHEAT,	
        NH_CSS_COLOR_NAME_WHITE,	
        NH_CSS_COLOR_NAME_WHITE_SMOKE,  	
        NH_CSS_COLOR_NAME_YELLOW,	
        NH_CSS_COLOR_NAME_YELLOW_GREEN,  
    } NH_CSS_COLOR_NAME;

    typedef enum NH_CSS_PSEUDO_CLASS {
        NH_CSS_PSEUDO_CLASS_ACTIVE,
        NH_CSS_PSEUDO_CLASS_ANY_LINK,
        NH_CSS_PSEUDO_CLASS_BLANK, 
        NH_CSS_PSEUDO_CLASS_CHECKED,
        NH_CSS_PSEUDO_CLASS_CURRENT, 
        NH_CSS_PSEUDO_CLASS_DEFAULT,
        NH_CSS_PSEUDO_CLASS_DEFINED,
        NH_CSS_PSEUDO_CLASS_DIR, 
        NH_CSS_PSEUDO_CLASS_DISABLED,
        NH_CSS_PSEUDO_CLASS_DROP, 
        NH_CSS_PSEUDO_CLASS_EMPTY,
        NH_CSS_PSEUDO_CLASS_ENABLED,
        NH_CSS_PSEUDO_CLASS_FIRST,
        NH_CSS_PSEUDO_CLASS_FIRST_CHILD,
        NH_CSS_PSEUDO_CLASS_FIRST_OF_TYPE,
        NH_CSS_PSEUDO_CLASS_FULLSCREEN, 
        NH_CSS_PSEUDO_CLASS_FUTURE, 
        NH_CSS_PSEUDO_CLASS_FOCUS,
        NH_CSS_PSEUDO_CLASS_FOCUS_VISIBLE,
        NH_CSS_PSEUDO_CLASS_FOCUS_WITHIN,
        NH_CSS_PSEUDO_CLASS_HAS, 
        NH_CSS_PSEUDO_CLASS_HOST,
        NH_CSS_PSEUDO_CLASS_HOST_,
        NH_CSS_PSEUDO_CLASS_HOST_CONTEXT,
        NH_CSS_PSEUDO_CLASS_HOVER,
        NH_CSS_PSEUDO_CLASS_INDETERMINATE,
        NH_CSS_PSEUDO_CLASS_IN_RANGE,
        NH_CSS_PSEUDO_CLASS_INVALID,
        NH_CSS_PSEUDO_CLASS_IS,
        NH_CSS_PSEUDO_CLASS_LANG,
        NH_CSS_PSEUDO_CLASS_LAST_CHILD,
        NH_CSS_PSEUDO_CLASS_LAST_OF_TYPE,
        NH_CSS_PSEUDO_CLASS_LEFT,
        NH_CSS_PSEUDO_CLASS_LINK,
        NH_CSS_PSEUDO_CLASS_LOCAL_LINK, 
        NH_CSS_PSEUDO_CLASS_NOT,
        NH_CSS_PSEUDO_CLASS_NTH_CHILD,
        NH_CSS_PSEUDO_CLASS_NTH_COL, 
        NH_CSS_PSEUDO_CLASS_NTH_LAST_CHILD,
        NH_CSS_PSEUDO_CLASS_NTH_LAST_COL, 
        NH_CSS_PSEUDO_CLASS_NTH_LAST_OF_TYPE,
        NH_CSS_PSEUDO_CLASS_NTH_OF_TYPE,
        NH_CSS_PSEUDO_CLASS_ONLY_CHILD,
        NH_CSS_PSEUDO_CLASS_ONLY_OF_TYPE,
        NH_CSS_PSEUDO_CLASS_OPTIONAL,
        NH_CSS_PSEUDO_CLASS_OUT_OF_RANGE,
        NH_CSS_PSEUDO_CLASS_PAST, 
        NH_CSS_PSEUDO_CLASS_PLACEHOLDER_SHOWN,
        NH_CSS_PSEUDO_CLASS_READ_ONLY,
        NH_CSS_PSEUDO_CLASS_READ_WRITE,
        NH_CSS_PSEUDO_CLASS_REQUIRED,
        NH_CSS_PSEUDO_CLASS_RIGHT,
        NH_CSS_PSEUDO_CLASS_ROOT,
        NH_CSS_PSEUDO_CLASS_SCOPE,
        NH_CSS_PSEUDO_CLASS_TARGET,
        NH_CSS_PSEUDO_CLASS_TARGET_WITHIN, 
        NH_CSS_PSEUDO_CLASS_USER_INVALID,
        NH_CSS_PSEUDO_CLASS_VALID,
        NH_CSS_PSEUDO_CLASS_VISITED,
        NH_CSS_PSEUDO_CLASS_WHERE, 
    } NH_CSS_PSEUDO_CLASS;

    typedef enum NH_CSS_PSEUDO_ELEMENT {
        NH_CSS_PSEUDO_ELEMENT_AFTER,
        NH_CSS_PSEUDO_ELEMENT_BACKDROP,
        NH_CSS_PSEUDO_ELEMENT_BEFORE,
        NH_CSS_PSEUDO_ELEMENT_CUE,
        NH_CSS_PSEUDO_ELEMENT_CUE_REGION,
        NH_CSS_PSEUDO_ELEMENT_FIRST_LETTER,
        NH_CSS_PSEUDO_ELEMENT_FIRST_LINE,
        NH_CSS_PSEUDO_ELEMENT_GRAMMAR_ERROR,
        NH_CSS_PSEUDO_ELEMENT_MARKER,
        NH_CSS_PSEUDO_ELEMENT_PART,
        NH_CSS_PSEUDO_ELEMENT_PLACEHOLDER,
        NH_CSS_PSEUDO_ELEMENT_SELECTION,
        NH_CSS_PSEUDO_ELEMENT_SLOTTED,
        NH_CSS_PSEUDO_ELEMENT_SPELLING_ERROR,
    } NH_CSS_PSEUDO_ELEMENT;

/** @} */

/** @addtogroup CSSFunctions Functions
 *  \ingroup CSS
 *  @{
 */

    const char** Nh_CSS_getPseudoClassNames(
        size_t *size_p
    );

    const char** Nh_CSS_getPseudoElementNames(
        size_t *size_p
    );

    NH_RESULT Nh_CSS_getColorFromName(
        char *name_p, char *hex_p
    );
    
    const char** Nh_CSS_getColorNames(
        size_t *size_p
    );

/** @} */

#endif 
