#ifndef NH_CSS_PROPERTIES_H
#define NH_CSS_PROPERTIES_H

#ifndef DOXYGEN_SHOULD_SKIP_THIS

/**
 * Netzhaut - Web Browser Engine
 * Copyright (C) 2022  Dajo Frey
 * Published under GNU LGPL. See Netzhaut/LICENSE.LGPL file.
 */

#include "../Parser/Parser.h"

#include "../Common/Includes.h"

#endif

/** @addtogroup lib_nhcss_enums
 *  @{
 */

    typedef enum NH_CSS_PROPERTY {
        NH_CSS_PROPERTY_AZIMUTH = 0,
        NH_CSS_PROPERTY_BACKGROUND_ATTACHMENT,
        NH_CSS_PROPERTY_BACKGROUND_COLOR,
        NH_CSS_PROPERTY_BACKGROUND_IMAGE,
        NH_CSS_PROPERTY_BACKGROUND_POSITION,
        NH_CSS_PROPERTY_BACKGROUND_REPEAT,
        NH_CSS_PROPERTY_BACKGROUND,
        NH_CSS_PROPERTY_BORDER_COLLAPSE,
        NH_CSS_PROPERTY_BORDER_COLOR,
        NH_CSS_PROPERTY_BORDER_SPACING,
        NH_CSS_PROPERTY_BORDER_STYLE,
        NH_CSS_PROPERTY_BORDER_RADIUS,
        NH_CSS_PROPERTY_BORDER_TOP,
        NH_CSS_PROPERTY_BORDER_RIGHT,
        NH_CSS_PROPERTY_BORDER_BOTTOM, 
        NH_CSS_PROPERTY_BORDER_LEFT,
        NH_CSS_PROPERTY_BORDER_TOP_COLOR,
        NH_CSS_PROPERTY_BORDER_RIGHT_COLOR, 
        NH_CSS_PROPERTY_BORDER_BOTTOM_COLOR, 
        NH_CSS_PROPERTY_BORDER_LEFT_COLOR,
        NH_CSS_PROPERTY_BORDER_TOP_STYLE, 
        NH_CSS_PROPERTY_BORDER_RIGHT_STYLE, 
        NH_CSS_PROPERTY_BORDER_BOTTOM_STYLE, 
        NH_CSS_PROPERTY_BORDER_LEFT_STYLE,
        NH_CSS_PROPERTY_BORDER_TOP_WIDTH, 
        NH_CSS_PROPERTY_BORDER_RIGHT_WIDTH, 
        NH_CSS_PROPERTY_BORDER_BOTTOM_WIDTH,
        NH_CSS_PROPERTY_BORDER_LEFT_WIDTH,
        NH_CSS_PROPERTY_BORDER_WIDTH,
        NH_CSS_PROPERTY_BORDER_TOP_LEFT_RADIUS,
        NH_CSS_PROPERTY_BORDER_TOP_RIGHT_RADIUS,
        NH_CSS_PROPERTY_BORDER_BOTTOM_LEFT_RADIUS,
        NH_CSS_PROPERTY_BORDER_BOTTOM_RIGHT_RADIUS,
        NH_CSS_PROPERTY_BORDER,
        NH_CSS_PROPERTY_BOTTOM,
        NH_CSS_PROPERTY_CAPTION_SIDE,
        NH_CSS_PROPERTY_CLEAR,
        NH_CSS_PROPERTY_CLIP,
        NH_CSS_PROPERTY_COLOR,
        NH_CSS_PROPERTY_CONTENT,
        NH_CSS_PROPERTY_COUNTER_INCREMENT,
        NH_CSS_PROPERTY_COUNTER_RESET,
        NH_CSS_PROPERTY_CUE_AFTER,
        NH_CSS_PROPERTY_CUE_BEFORE,
        NH_CSS_PROPERTY_CUE,
        NH_CSS_PROPERTY_CURSOR,
        NH_CSS_PROPERTY_DIRECTION,
        NH_CSS_PROPERTY_DISPLAY,
        NH_CSS_PROPERTY_ELEVATION,
        NH_CSS_PROPERTY_EMPTY_CELLS,
        NH_CSS_PROPERTY_FLOAT,
        NH_CSS_PROPERTY_FONT_FAMILY,
        NH_CSS_PROPERTY_FONT_SIZE,
        NH_CSS_PROPERTY_FONT_STYLE,
        NH_CSS_PROPERTY_FONT_VARIANT,
        NH_CSS_PROPERTY_FONT_WEIGHT,
        NH_CSS_PROPERTY_FONT,
        NH_CSS_PROPERTY_HEIGHT,
        NH_CSS_PROPERTY_LEFT,
        NH_CSS_PROPERTY_LETTER_SPACING,
        NH_CSS_PROPERTY_LINE_HEIGHT,
        NH_CSS_PROPERTY_LIST_STYLE_IMAGE,
        NH_CSS_PROPERTY_LIST_STYLE_POSITION,
        NH_CSS_PROPERTY_LIST_STYLE_TYPE,
        NH_CSS_PROPERTY_LIST_STYLE,
        NH_CSS_PROPERTY_MARGIN_RIGHT,
        NH_CSS_PROPERTY_MARGIN_LEFT,
        NH_CSS_PROPERTY_MARGIN_TOP,
        NH_CSS_PROPERTY_MARGIN_BOTTOM,
        NH_CSS_PROPERTY_MARGIN,
        NH_CSS_PROPERTY_MARGIN_BLOCK_START, 
        NH_CSS_PROPERTY_MARGIN_BLOCK_END, 
        NH_CSS_PROPERTY_MARGIN_INLINE_START, 
        NH_CSS_PROPERTY_MARGIN_INLINE_END,
        NH_CSS_PROPERTY_MARGIN_BLOCK, 
        NH_CSS_PROPERTY_MARGIN_INLINE,
        NH_CSS_PROPERTY_MAX_HEIGHT,
        NH_CSS_PROPERTY_MAX_WIDTH,
        NH_CSS_PROPERTY_MIN_HEIGHT,
        NH_CSS_PROPERTY_MIN_WIDTH,
        NH_CSS_PROPERTY_ORPHANS,
        NH_CSS_PROPERTY_OUTLINE_COLOR,
        NH_CSS_PROPERTY_OUTLINE_STYLE,
        NH_CSS_PROPERTY_OUTLINE_WIDTH,
        NH_CSS_PROPERTY_OUTLINE,
        NH_CSS_PROPERTY_OVERFLOW,
        NH_CSS_PROPERTY_PADDING_TOP,
        NH_CSS_PROPERTY_PADDING_RIGHT, 
        NH_CSS_PROPERTY_PADDING_BOTTOM,
        NH_CSS_PROPERTY_PADDING_LEFT,
        NH_CSS_PROPERTY_PADDING,
        NH_CSS_PROPERTY_PAGE_BREAK_AFTER,
        NH_CSS_PROPERTY_PAGE_BREAK_BEFORE,
        NH_CSS_PROPERTY_PAGE_BREAK_INSIDE,
        NH_CSS_PROPERTY_PAUSE_AFTER,
        NH_CSS_PROPERTY_PAUSE_BEFORE,
        NH_CSS_PROPERTY_PAUSE,
        NH_CSS_PROPERTY_PITCH_RANGE,
        NH_CSS_PROPERTY_PITCH,
        NH_CSS_PROPERTY_PLAY_DURING,
        NH_CSS_PROPERTY_POSITION,
        NH_CSS_PROPERTY_QUOTES,
        NH_CSS_PROPERTY_RICHNESS,
        NH_CSS_PROPERTY_RIGHT,
        NH_CSS_PROPERTY_SPEAK_HEADER,
        NH_CSS_PROPERTY_SPEAK_NUMERAL,
        NH_CSS_PROPERTY_SPEAK_PUNCTUATION,
        NH_CSS_PROPERTY_SPEAK,
        NH_CSS_PROPERTY_SPEECH_RATE,
        NH_CSS_PROPERTY_STRESS,
        NH_CSS_PROPERTY_TABLE_LAYOUT,
        NH_CSS_PROPERTY_TEXT_ALIGN,
        NH_CSS_PROPERTY_TEXT_ALIGN_ALL,
        NH_CSS_PROPERTY_TEXT_ALIGN_LAST,
        NH_CSS_PROPERTY_TEXT_DECORATION,
        NH_CSS_PROPERTY_TEXT_INDENT,
        NH_CSS_PROPERTY_TEXT_ORIENTATION,
        NH_CSS_PROPERTY_TEXT_TRANSFORM,
        NH_CSS_PROPERTY_TOP,
        NH_CSS_PROPERTY_UNICODE_BIDI,
        NH_CSS_PROPERTY_VERTICAL_ALIGN,
        NH_CSS_PROPERTY_VISIBILITY,
        NH_CSS_PROPERTY_VOICE_FAMILY,
        NH_CSS_PROPERTY_VOLUME,
        NH_CSS_PROPERTY_WHITE_SPACE,
        NH_CSS_PROPERTY_WIDOWS,
        NH_CSS_PROPERTY_WIDTH, 
        NH_CSS_PROPERTY_WORD_BREAK,
        NH_CSS_PROPERTY_WORD_SPACING,
        NH_CSS_PROPERTY_WRITING_MODE, /**<This property specifies whether lines of text are laid out horizontally or vertically and the direction in which blocks progress.*/
        NH_CSS_PROPERTY_Z_INDEX, 
        NH_CSS_PROPERTY_COUNT,
    } NH_CSS_PROPERTY;

/** @} */

/** @addtogroup lib_nhcss_vars
 *  @{
 */

    extern const NH_BYTE *NH_CSS_PROPERTY_NAMES_PP[];
    extern const NH_BOOL NH_CSS_PROPERTY_INHERITED_P[];

/** @} */

/** @addtogroup lib_nhcss_functions
 *  @{
 */

    NH_CSS_RESULT nh_css_createInitialPropertyValues(
    );

    nh_css_ComponentValueData *nh_css_getInitialComponentValueData(
        NH_CSS_PROPERTY property
    );

/** @} */

#endif
