// LICENSE NOTICE ==================================================================================

/**
 * Netzhaut - Web Browser Engine
 * Copyright (C) 2020  Dajo Frey
 * Published under LGPLv3
 *
 * This file was generated by NhInstaller
 */

// INCLUDE =========================================================================================

#include "Builtin.h"

#include "../Specs/DOM/TreeWalker.idl.h"
#include "../Specs/DOM/Text.idl.h"
#include "../Specs/DOM/StaticRange.idl.h"
#include "../Specs/DOM/Slottable.idl.h"
#include "../Specs/DOM/ShadowRoot.idl.h"
#include "../Specs/DOM/Range.idl.h"
#include "../Specs/DOM/ProcessingInstruction.idl.h"
#include "../Specs/DOM/ParentNode.idl.h"
#include "../Specs/DOM/NonElementParentNode.idl.h"
#include "../Specs/DOM/NonDocumentTypeChildNode.idl.h"
#include "../Specs/DOM/NodeList.idl.h"
#include "../Specs/DOM/NodeIterator.idl.h"
#include "../Specs/DOM/NodeFilter.idl.h"
#include "../Specs/DOM/Node.idl.h"
#include "../Specs/DOM/NamedNodeMap.idl.h"
#include "../Specs/DOM/MutationRecord.idl.h"
#include "../Specs/DOM/MutationObserver.idl.h"
#include "../Specs/DOM/HTMLCollection.idl.h"
#include "../Specs/DOM/EventTarget.idl.h"
#include "../Specs/DOM/Event.idl.h"
#include "../Specs/DOM/Element.idl.h"
#include "../Specs/DOM/DocumentType.idl.h"
#include "../Specs/DOM/DocumentOrShadowRoot.idl.h"
#include "../Specs/DOM/DocumentFragment.idl.h"
#include "../Specs/DOM/Document.idl.h"
#include "../Specs/DOM/DOMTokenList.idl.h"
#include "../Specs/DOM/DOMImplementation.idl.h"
#include "../Specs/DOM/Comment.idl.h"
#include "../Specs/DOM/ChildNode.idl.h"
#include "../Specs/DOM/CharacterData.idl.h"
#include "../Specs/DOM/CDataSection.idl.h"
#include "../Specs/DOM/Attr.idl.h"
#include "../Specs/DOM/AbstractRange.idl.h"
#include "../Specs/DOM/AbortSignal.idl.h"
#include "../Specs/DOM/AbortController.idl.h"
#include "../Specs/HTML/Document.idl.h"
#include "../Specs/HTML/DocumentOrShadowRoot.idl.h"
#include "../Specs/HTML/HTMLElement.idl.h"
#include "../Specs/HTML/HTMLOrSVGElement.idl.h"

// FRAGMENT NAMES ==================================================================================

NH_BYTE *NH_WEBIDL_FRAGMENT_NAMES_PP[] = {
    "DOM_TreeWalker",
    "DOM_Text",
    "DOM_StaticRange",
    "DOM_Slottable",
    "DOM_ShadowRoot",
    "DOM_Range",
    "DOM_ProcessingInstruction",
    "DOM_ParentNode",
    "DOM_NonElementParentNode",
    "DOM_NonDocumentTypeChildNode",
    "DOM_NodeList",
    "DOM_NodeIterator",
    "DOM_NodeFilter",
    "DOM_Node",
    "DOM_NamedNodeMap",
    "DOM_MutationRecord",
    "DOM_MutationObserver",
    "DOM_HTMLCollection",
    "DOM_EventTarget",
    "DOM_Event",
    "DOM_Element",
    "DOM_DocumentType",
    "DOM_DocumentOrShadowRoot",
    "DOM_DocumentFragment",
    "DOM_Document",
    "DOM_DOMTokenList",
    "DOM_DOMImplementation",
    "DOM_Comment",
    "DOM_ChildNode",
    "DOM_CharacterData",
    "DOM_CDataSection",
    "DOM_Attr",
    "DOM_AbstractRange",
    "DOM_AbortSignal",
    "DOM_AbortController",
    "HTML_Document",
    "HTML_DocumentOrShadowRoot",
    "HTML_HTMLElement",
    "HTML_HTMLOrSVGElement",
};

size_t NH_WEBIDL_FRAGMENT_NAMES_PP_COUNT = sizeof(NH_WEBIDL_FRAGMENT_NAMES_PP) / sizeof(NH_WEBIDL_FRAGMENT_NAMES_PP[0]);

// FRAGMENTS =======================================================================================

unsigned NH_BYTE *NH_WEBIDL_FRAGMENTS_PP[] = {
    Nh_WebIDL_DOM_TreeWalker_p,
    Nh_WebIDL_DOM_Text_p,
    Nh_WebIDL_DOM_StaticRange_p,
    Nh_WebIDL_DOM_Slottable_p,
    Nh_WebIDL_DOM_ShadowRoot_p,
    Nh_WebIDL_DOM_Range_p,
    Nh_WebIDL_DOM_ProcessingInstruction_p,
    Nh_WebIDL_DOM_ParentNode_p,
    Nh_WebIDL_DOM_NonElementParentNode_p,
    Nh_WebIDL_DOM_NonDocumentTypeChildNode_p,
    Nh_WebIDL_DOM_NodeList_p,
    Nh_WebIDL_DOM_NodeIterator_p,
    Nh_WebIDL_DOM_NodeFilter_p,
    Nh_WebIDL_DOM_Node_p,
    Nh_WebIDL_DOM_NamedNodeMap_p,
    Nh_WebIDL_DOM_MutationRecord_p,
    Nh_WebIDL_DOM_MutationObserver_p,
    Nh_WebIDL_DOM_HTMLCollection_p,
    Nh_WebIDL_DOM_EventTarget_p,
    Nh_WebIDL_DOM_Event_p,
    Nh_WebIDL_DOM_Element_p,
    Nh_WebIDL_DOM_DocumentType_p,
    Nh_WebIDL_DOM_DocumentOrShadowRoot_p,
    Nh_WebIDL_DOM_DocumentFragment_p,
    Nh_WebIDL_DOM_Document_p,
    Nh_WebIDL_DOM_DOMTokenList_p,
    Nh_WebIDL_DOM_DOMImplementation_p,
    Nh_WebIDL_DOM_Comment_p,
    Nh_WebIDL_DOM_ChildNode_p,
    Nh_WebIDL_DOM_CharacterData_p,
    Nh_WebIDL_DOM_CDataSection_p,
    Nh_WebIDL_DOM_Attr_p,
    Nh_WebIDL_DOM_AbstractRange_p,
    Nh_WebIDL_DOM_AbortSignal_p,
    Nh_WebIDL_DOM_AbortController_p,
    Nh_WebIDL_HTML_Document_p,
    Nh_WebIDL_HTML_DocumentOrShadowRoot_p,
    Nh_WebIDL_HTML_HTMLElement_p,
    Nh_WebIDL_HTML_HTMLOrSVGElement_p,
};

size_t NH_WEBIDL_FRAGMENTS_PP_COUNT = sizeof(NH_WEBIDL_FRAGMENTS_PP) / sizeof(NH_WEBIDL_FRAGMENTS_PP[0]);

// FRAGMENT LENGTHS =================================================================================

const unsigned int NH_WEBIDL_FRAGMENT_LENGTHS_P[] = {
    Nh_WebIDL_DOM_TreeWalker_p_len,
    Nh_WebIDL_DOM_Text_p_len,
    Nh_WebIDL_DOM_StaticRange_p_len,
    Nh_WebIDL_DOM_Slottable_p_len,
    Nh_WebIDL_DOM_ShadowRoot_p_len,
    Nh_WebIDL_DOM_Range_p_len,
    Nh_WebIDL_DOM_ProcessingInstruction_p_len,
    Nh_WebIDL_DOM_ParentNode_p_len,
    Nh_WebIDL_DOM_NonElementParentNode_p_len,
    Nh_WebIDL_DOM_NonDocumentTypeChildNode_p_len,
    Nh_WebIDL_DOM_NodeList_p_len,
    Nh_WebIDL_DOM_NodeIterator_p_len,
    Nh_WebIDL_DOM_NodeFilter_p_len,
    Nh_WebIDL_DOM_Node_p_len,
    Nh_WebIDL_DOM_NamedNodeMap_p_len,
    Nh_WebIDL_DOM_MutationRecord_p_len,
    Nh_WebIDL_DOM_MutationObserver_p_len,
    Nh_WebIDL_DOM_HTMLCollection_p_len,
    Nh_WebIDL_DOM_EventTarget_p_len,
    Nh_WebIDL_DOM_Event_p_len,
    Nh_WebIDL_DOM_Element_p_len,
    Nh_WebIDL_DOM_DocumentType_p_len,
    Nh_WebIDL_DOM_DocumentOrShadowRoot_p_len,
    Nh_WebIDL_DOM_DocumentFragment_p_len,
    Nh_WebIDL_DOM_Document_p_len,
    Nh_WebIDL_DOM_DOMTokenList_p_len,
    Nh_WebIDL_DOM_DOMImplementation_p_len,
    Nh_WebIDL_DOM_Comment_p_len,
    Nh_WebIDL_DOM_ChildNode_p_len,
    Nh_WebIDL_DOM_CharacterData_p_len,
    Nh_WebIDL_DOM_CDataSection_p_len,
    Nh_WebIDL_DOM_Attr_p_len,
    Nh_WebIDL_DOM_AbstractRange_p_len,
    Nh_WebIDL_DOM_AbortSignal_p_len,
    Nh_WebIDL_DOM_AbortController_p_len,
    Nh_WebIDL_HTML_Document_p_len,
    Nh_WebIDL_HTML_DocumentOrShadowRoot_p_len,
    Nh_WebIDL_HTML_HTMLElement_p_len,
    Nh_WebIDL_HTML_HTMLOrSVGElement_p_len,
};
