[Exposed=Window]
interface NodeList {
  private attribute * nodes;
  private attribute unsigned long chunks;
  getter Node? item(unsigned long index);
  readonly attribute unsigned long length;
  iterable<Node>;
};
