[Exposed=Window]
interface NodeList {
  private attribute List nodes;
  private boolean append(Node node);
  private boolean remove(Node node);
  getter Node? item(unsigned long index);
  readonly attribute unsigned long length;
  iterable<Node>;
};
