#ifndef NH_UNICODE_LOOKUP_H
#define NH_UNICODE_LOOKUP_H

#ifndef DOXYGEN_SHOULD_SKIP_THIS

/**
 * Netzhaut - Web Browser Engine
 * Copyright (C) 2020  Dajo Frey
 * Published under LGPLv3
 *
 * This file was generated by the NhInstaller Library
 */

#include "String.h"

#endif

/** @addtogroup CoreDefines Defines
*  \ingroup Core
 *  @{
 */

    #define NH_UNICODE_LOOKUP_COUNT 34279
    #define NH_UNICODE_LOOKUP_UNDEFINED_RANGES_COUNT 693

/** @} */

/** @addtogroup CoreData Data
*  \ingroup Core
 *  @{
 */

    extern const NH_BYTE NH_UNICODE_LOOKUP_PP[34279][255];
    extern const long NH_UNICODE_LOOKUP_UNDEFINED_RANGES_PP[693][2];

/** @} */

#endif