// LICENSE NOTICE ==================================================================================

/**
 * Netzhaut - Web Browser Engine
 * Copyright (C) 2020  Dajo Frey
 * Published under LGPLv3
 *
 * This file was generated by NhInstaller
 */

// INCLUDE =========================================================================================

#include "Builtin.h"

#include "../Specs/DOM/TreeWalker.web.h"
#include "../Specs/DOM/Text.web.h"
#include "../Specs/DOM/StaticRange.web.h"
#include "../Specs/DOM/Slottable.web.h"
#include "../Specs/DOM/ShadowRoot.web.h"
#include "../Specs/DOM/Range.web.h"
#include "../Specs/DOM/ProcessingInstruction.web.h"
#include "../Specs/DOM/ParentNode.web.h"
#include "../Specs/DOM/NonElementParentNode.web.h"
#include "../Specs/DOM/NonDocumentTypeChildNode.web.h"
#include "../Specs/DOM/NodeList.web.h"
#include "../Specs/DOM/NodeIterator.web.h"
#include "../Specs/DOM/NodeFilter.web.h"
#include "../Specs/DOM/Node.web.h"
#include "../Specs/DOM/NamedNodeMap.web.h"
#include "../Specs/DOM/MutationRecord.web.h"
#include "../Specs/DOM/MutationObserver.web.h"
#include "../Specs/DOM/HTMLCollection.web.h"
#include "../Specs/DOM/EventTarget.web.h"
#include "../Specs/DOM/Event.web.h"
#include "../Specs/DOM/Element.web.h"
#include "../Specs/DOM/DocumentType.web.h"
#include "../Specs/DOM/DocumentOrShadowRoot.web.h"
#include "../Specs/DOM/DocumentFragment.web.h"
#include "../Specs/DOM/Document.web.h"
#include "../Specs/DOM/DOMTokenList.web.h"
#include "../Specs/DOM/DOMImplementation.web.h"
#include "../Specs/DOM/Comment.web.h"
#include "../Specs/DOM/ChildNode.web.h"
#include "../Specs/DOM/CharacterData.web.h"
#include "../Specs/DOM/CDataSection.web.h"
#include "../Specs/DOM/Attr.web.h"
#include "../Specs/DOM/AbstractRange.web.h"
#include "../Specs/DOM/AbortSignal.web.h"
#include "../Specs/DOM/AbortController.web.h"
#include "../Specs/HTML/Document.web.h"
#include "../Specs/HTML/DocumentOrShadowRoot.web.h"
#include "../Specs/HTML/HTMLElement.web.h"
#include "../Specs/HTML/HTMLOrSVGElement.web.h"

// FRAGMENT NAMES ==================================================================================

NH_BYTE *NH_WEB_FRAGMENT_NAMES_PP[] = {
    "DOM_TreeWalker",
    "DOM_Text",
    "DOM_StaticRange",
    "DOM_Slottable",
    "DOM_ShadowRoot",
    "DOM_Range",
    "DOM_ProcessingInstruction",
    "DOM_ParentNode",
    "DOM_NonElementParentNode",
    "DOM_NonDocumentTypeChildNode",
    "DOM_NodeList",
    "DOM_NodeIterator",
    "DOM_NodeFilter",
    "DOM_Node",
    "DOM_NamedNodeMap",
    "DOM_MutationRecord",
    "DOM_MutationObserver",
    "DOM_HTMLCollection",
    "DOM_EventTarget",
    "DOM_Event",
    "DOM_Element",
    "DOM_DocumentType",
    "DOM_DocumentOrShadowRoot",
    "DOM_DocumentFragment",
    "DOM_Document",
    "DOM_DOMTokenList",
    "DOM_DOMImplementation",
    "DOM_Comment",
    "DOM_ChildNode",
    "DOM_CharacterData",
    "DOM_CDataSection",
    "DOM_Attr",
    "DOM_AbstractRange",
    "DOM_AbortSignal",
    "DOM_AbortController",
    "HTML_Document",
    "HTML_DocumentOrShadowRoot",
    "HTML_HTMLElement",
    "HTML_HTMLOrSVGElement",
};

size_t NH_WEB_FRAGMENT_NAMES_PP_COUNT = sizeof(NH_WEB_FRAGMENT_NAMES_PP) / sizeof(NH_WEB_FRAGMENT_NAMES_PP[0]);

// FRAGMENTS =======================================================================================

unsigned NH_BYTE *NH_WEB_FRAGMENTS_PP[] = {
    Nh_Web_DOM_TreeWalker_p,
    Nh_Web_DOM_Text_p,
    Nh_Web_DOM_StaticRange_p,
    Nh_Web_DOM_Slottable_p,
    Nh_Web_DOM_ShadowRoot_p,
    Nh_Web_DOM_Range_p,
    Nh_Web_DOM_ProcessingInstruction_p,
    Nh_Web_DOM_ParentNode_p,
    Nh_Web_DOM_NonElementParentNode_p,
    Nh_Web_DOM_NonDocumentTypeChildNode_p,
    Nh_Web_DOM_NodeList_p,
    Nh_Web_DOM_NodeIterator_p,
    Nh_Web_DOM_NodeFilter_p,
    Nh_Web_DOM_Node_p,
    Nh_Web_DOM_NamedNodeMap_p,
    Nh_Web_DOM_MutationRecord_p,
    Nh_Web_DOM_MutationObserver_p,
    Nh_Web_DOM_HTMLCollection_p,
    Nh_Web_DOM_EventTarget_p,
    Nh_Web_DOM_Event_p,
    Nh_Web_DOM_Element_p,
    Nh_Web_DOM_DocumentType_p,
    Nh_Web_DOM_DocumentOrShadowRoot_p,
    Nh_Web_DOM_DocumentFragment_p,
    Nh_Web_DOM_Document_p,
    Nh_Web_DOM_DOMTokenList_p,
    Nh_Web_DOM_DOMImplementation_p,
    Nh_Web_DOM_Comment_p,
    Nh_Web_DOM_ChildNode_p,
    Nh_Web_DOM_CharacterData_p,
    Nh_Web_DOM_CDataSection_p,
    Nh_Web_DOM_Attr_p,
    Nh_Web_DOM_AbstractRange_p,
    Nh_Web_DOM_AbortSignal_p,
    Nh_Web_DOM_AbortController_p,
    Nh_Web_HTML_Document_p,
    Nh_Web_HTML_DocumentOrShadowRoot_p,
    Nh_Web_HTML_HTMLElement_p,
    Nh_Web_HTML_HTMLOrSVGElement_p,
};

size_t NH_WEB_FRAGMENTS_PP_COUNT = sizeof(NH_WEB_FRAGMENTS_PP) / sizeof(NH_WEB_FRAGMENTS_PP[0]);

// FRAGMENT LENGTHS =================================================================================

const unsigned int NH_WEB_FRAGMENT_LENGTHS_P[] = {
    Nh_Web_DOM_TreeWalker_p_len,
    Nh_Web_DOM_Text_p_len,
    Nh_Web_DOM_StaticRange_p_len,
    Nh_Web_DOM_Slottable_p_len,
    Nh_Web_DOM_ShadowRoot_p_len,
    Nh_Web_DOM_Range_p_len,
    Nh_Web_DOM_ProcessingInstruction_p_len,
    Nh_Web_DOM_ParentNode_p_len,
    Nh_Web_DOM_NonElementParentNode_p_len,
    Nh_Web_DOM_NonDocumentTypeChildNode_p_len,
    Nh_Web_DOM_NodeList_p_len,
    Nh_Web_DOM_NodeIterator_p_len,
    Nh_Web_DOM_NodeFilter_p_len,
    Nh_Web_DOM_Node_p_len,
    Nh_Web_DOM_NamedNodeMap_p_len,
    Nh_Web_DOM_MutationRecord_p_len,
    Nh_Web_DOM_MutationObserver_p_len,
    Nh_Web_DOM_HTMLCollection_p_len,
    Nh_Web_DOM_EventTarget_p_len,
    Nh_Web_DOM_Event_p_len,
    Nh_Web_DOM_Element_p_len,
    Nh_Web_DOM_DocumentType_p_len,
    Nh_Web_DOM_DocumentOrShadowRoot_p_len,
    Nh_Web_DOM_DocumentFragment_p_len,
    Nh_Web_DOM_Document_p_len,
    Nh_Web_DOM_DOMTokenList_p_len,
    Nh_Web_DOM_DOMImplementation_p_len,
    Nh_Web_DOM_Comment_p_len,
    Nh_Web_DOM_ChildNode_p_len,
    Nh_Web_DOM_CharacterData_p_len,
    Nh_Web_DOM_CDataSection_p_len,
    Nh_Web_DOM_Attr_p_len,
    Nh_Web_DOM_AbstractRange_p_len,
    Nh_Web_DOM_AbortSignal_p_len,
    Nh_Web_DOM_AbortController_p_len,
    Nh_Web_HTML_Document_p_len,
    Nh_Web_HTML_DocumentOrShadowRoot_p_len,
    Nh_Web_HTML_HTMLElement_p_len,
    Nh_Web_HTML_HTMLOrSVGElement_p_len,
};
