#ifndef NH_HTML_HTMLELEMENT_H
#define NH_HTML_HTMLELEMENT_H

#ifndef DOXYGEN_SHOULD_SKIP_THIS

/**
 * Netzhaut - Web Browser Engine
 * Copyright (C) 2020  Dajo Frey
 * Published under LGPLv3
 *
 * This file was generated by NhWebIDLSerializer
 */

#endif

/** @addtogroup NhFunctions Functions
 *  @{
 */

    Nh_ECMAScript_Type Nh_HTML_HTMLElement_constructor(
        Nh_WebIDL_Object *This_p, Nh_List Arguments
    );

    Nh_ECMAScript_Type Nh_HTML_HTMLElement_click(
        Nh_WebIDL_Object *This_p, Nh_List Arguments
    );

    Nh_ECMAScript_Type Nh_HTML_HTMLElement_attachInternals(
        Nh_WebIDL_Object *This_p, Nh_List Arguments
    );

/** @} */

#endif