#ifndef NH_HTML_HTMLORSVGELEMENT_H
#define NH_HTML_HTMLORSVGELEMENT_H

#ifndef DOXYGEN_SHOULD_SKIP_THIS

/**
 * Netzhaut - Web Browser Engine
 * Copyright (C) 2020  Dajo Frey
 * Published under LGPLv3
 *
 * This file was generated by NhInstaller
 */

#endif

/** @addtogroup NhFunctions Functions
 *  @{
 */

    Nh_WebIDL_Result Nh_HTML_HTMLOrSVGElement_focus(
        Nh_WebIDL_Object *This_p, Nh_List Arguments
    );

    Nh_WebIDL_Result Nh_HTML_HTMLOrSVGElement_blur(
        Nh_WebIDL_Object *This_p, Nh_List Arguments
    );

/** @} */

#endif