// LICENSE NOTICE ==================================================================================

/**
 * Netzhaut - Web Browser Engine
 * Copyright (C) 2020  Dajo Frey
 * Published under LGPLv3
 */

// INCLUDE =========================================================================================

#include "Generator.h"
#include "Serializer.h"
#include "Util.h"

#include "../Common/Macro.h"
#include NH_WEBIDL_FLOW
#include NH_WEBIDL_DEFAULT_CHECK

#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>

#define NH_LICENSE_NOTICE \
    "/**\n * Netzhaut - Web Browser Engine\n * Copyright (C) 2020  Dajo Frey\n * Published under LGPLv3\n *\n * This file was generated by NhWebIDLGenerator\n */\n\n"

// HELPER ==========================================================================================

static NH_BOOL Nh_WebIDL_hasExtendedAttribute(
    Nh_Array ExtendedAttributes, NH_WEBIDL_EXTENDED_ATTRIBUTE type)
{
NH_WEBIDL_BEGIN()

    for (int i = 0; i < ExtendedAttributes.length; ++i) {
        Nh_WebIDL_ExtendedAttribute *ExtendedAttribute_p = 
            &((Nh_WebIDL_ExtendedAttribute*)ExtendedAttributes.bytes_p)[i];
        if (ExtendedAttribute_p->type == type) {
            NH_WEBIDL_END(NH_TRUE)
        }
    }

NH_WEBIDL_END(NH_FALSE)
}

static void Nh_WebIDL_stringifyOperationResult(
    Nh_WebIDL_Operation *Operation_p, char *result_p)
{
NH_WEBIDL_BEGIN()

    if (Nh_WebIDL_hasExtendedAttribute(Operation_p->ExtendedAttributes, NH_WEBIDL_EXTENDED_ATTRIBUTE_NEW_OBJECT)) {
        sprintf(result_p, "NH_WEBIDL_NEW_OBJECT");
    }
    else {
        sprintf(result_p, "Nh_ECMAScript_Type");
    }
   
NH_WEBIDL_SILENT_END()
}

// FRAGMENT DATA HEADER ============================================================================

static int fileCount = 0;
static char *files_pp[2048] = {NULL};

static int serializationDataCount = 0;
static Nh_WebIDL_SerializationData SerializationData_p[2048];

static NH_BOOL Nh_WebIDL_functionImplemented(
    char *runtimePath_p, char *fragmentName_p, char *operationName_p)
{
NH_WEBIDL_BEGIN()

    char str_p[1024] = {'\0'};
    strcpy(str_p, runtimePath_p);
    for (int i = strlen(str_p) - 1; str_p[i] != '/'; --i) {str_p[i] = '\0';}

    char tmp_p[1024] = {'\0'};
    strcpy(tmp_p, fragmentName_p);
    for (int i = 0; i < strlen(tmp_p); ++i) {if (tmp_p[i] == '_') {tmp_p[i] = '/';}}
    sprintf(str_p + strlen(str_p), "%s.idl.c", tmp_p);

    char *buffer_p = 0;
    long length;

    FILE *f = fopen(str_p, "r");
    if (f == NULL) {NH_WEBIDL_END(NH_FALSE)}

    fseek (f, 0, SEEK_END);
    length = ftell(f);
    fseek (f, 0, SEEK_SET);

    if (length > 0)
    {
        buffer_p = malloc(sizeof(char) * (length + 1));
        if (buffer_p) {fread(buffer_p, 1, length, f);}
        buffer_p[length] = '\0';

        sprintf(str_p, "Nh_WebIDL_%s_%s(\n", fragmentName_p, operationName_p);
        if (strstr(buffer_p, str_p)) {NH_WEBIDL_END(NH_TRUE)}

        free(buffer_p);
    }

    fclose(f);

NH_WEBIDL_END(NH_FALSE)
}

static NH_WEBIDL_RESULT Nh_WebIDL_createIncludes(
    FILE *f)
{
NH_WEBIDL_BEGIN()

    fprintf(f, "// INCLUDE =========================================================================================\n\n");
    fprintf(f, "#include \"FragmentData.h\"\n\n");

    for (int i = 0; i < fileCount; ++i) 
    {
        char fragmentName_p[1024] = {'\0'};
        Nh_WebIDL_getFragmentName(files_pp[i], fragmentName_p);

        for (int j = 0; j < strlen(fragmentName_p); ++j) {
            if (fragmentName_p[j] == '_') {
                fragmentName_p[j] = '/';
            }
        }

        fprintf(f,"#include \"../%s.idl.h\"\n", fragmentName_p);
    }

NH_WEBIDL_DIAGNOSTIC_END(NH_WEBIDL_SUCCESS)
}

static NH_WEBIDL_RESULT Nh_WebIDL_createFragmentNames(
    FILE *f, NH_BOOL asString)
{
NH_WEBIDL_BEGIN()

    if (asString) {
        fprintf(f, "\n// FRAGMENT NAMES ==================================================================================\n\n");
        fprintf(f, "const char *NH_WEBIDL_FRAGMENT_NAMES_PP[] = {\n");
    }
    else {
        fprintf(f, "\n// FRAGMENTS =======================================================================================\n\n");
        fprintf(f, "unsigned char *NH_WEBIDL_FRAGMENTS_PP[] = {\n");
    }

    for (int i = 0; i < fileCount; ++i) 
    {
        char fragmentName_p[1024] = {'\0'}, *p;
        Nh_WebIDL_getFragmentName(files_pp[i], fragmentName_p);
        fprintf(f, asString ? "    \"%s\",\n" : "    Nh_WebIDL_%s_p,\n", fragmentName_p);
    }

    fprintf(f, "};\n");

    if (asString) {
        fprintf(f, "\nsize_t NH_WEBIDL_FRAGMENT_NAMES_PP_COUNT = sizeof(NH_WEBIDL_FRAGMENT_NAMES_PP) / sizeof(NH_WEBIDL_FRAGMENT_NAMES_PP[0]);\n");
    }
    else {
        fprintf(f, "\nsize_t NH_WEBIDL_FRAGMENTS_PP_COUNT = sizeof(NH_WEBIDL_FRAGMENTS_PP) / sizeof(NH_WEBIDL_FRAGMENTS_PP[0]);\n");
    }

NH_WEBIDL_DIAGNOSTIC_END(NH_WEBIDL_SUCCESS)
}

static NH_WEBIDL_RESULT Nh_WebIDL_createFragmentFunctions(
    FILE *f, char *runtimePath_p, NH_BOOL asString, NH_WEBIDL_BINDING binding)
{
NH_WEBIDL_BEGIN()

    if (asString) {
        fprintf(f, "\n// FRAGMENT FUNCTION NAMES =========================================================================\n\n");
        fprintf(f, "const char *NH_WEBIDL_FRAGMENT_FUNCTION_NAMES_PP[] = {");
    }
    else {
        switch (binding) {
            case NH_WEBIDL_BINDING_ECMASCRIPT :
                fprintf(f, "\n// FRAGMENT FUNCTIONS ==============================================================================\n\n");
                fprintf(f, "Nh_WebIDL_Result (*NH_WEBIDL_FRAGMENT_FUNCTIONS_PP[]) (Nh_ECMAScript_Object *This_p, Nh_List Arguments) = {");
                break;
        }
    }

    for (int i = 0; i < serializationDataCount; ++i) 
    {
        Nh_WebIDL_Fragment Fragment = SerializationData_p[i].Fragment;

        char fragmentName_p[1024] = {'\0'};
        Nh_WebIDL_getFragmentName(files_pp[i], fragmentName_p);

        for (int j = 0; j < Fragment.definitionCount; ++j)
        {
            switch (Fragment.Definitions_p[j].type)
            {
                case NH_WEBIDL_DEFINITION_CALLBACK           : break; 
                case NH_WEBIDL_DEFINITION_CALLBACK_INTERFACE : break;
                case NH_WEBIDL_DEFINITION_INTERFACE          : 
                {
                    Nh_WebIDL_Interface *Interface_p = Fragment.Definitions_p[j].data_p;
                    for (int k = 0; k < Interface_p->Operations.length; ++k)
                    {
                        Nh_WebIDL_Operation *Operation_p = &((Nh_WebIDL_Operation*)Interface_p->Operations.bytes_p)[k];
                        if (Nh_WebIDL_functionImplemented(runtimePath_p, fragmentName_p, Operation_p->name_p)) {
                            fprintf(f, asString ? "\n    \"%s_%s\"," : "\n    Nh_WebIDL_%s_%s,", fragmentName_p, Operation_p->name_p);
                        }
                        else {
                            fprintf(f, asString ? "\n//    \"%s_%s\"," : "\n//    Nh_WebIDL_%s_%s,", fragmentName_p, Operation_p->name_p);
                        }
                    } 
                    break;
                }
                case NH_WEBIDL_DEFINITION_INTERFACE_MIXIN    : break; 
                case NH_WEBIDL_DEFINITION_MIXIN              : break;
                case NH_WEBIDL_DEFINITION_NAMESPACE          : break;
                case NH_WEBIDL_DEFINITION_PARTIAL            : break;
                case NH_WEBIDL_DEFINITION_DICTIONARY         : break; 
                case NH_WEBIDL_DEFINITION_ENUM               : break;
                case NH_WEBIDL_DEFINITION_TYPEDEF            : break;
                case NH_WEBIDL_DEFINITION_INCLUDES_STATEMENT : break;
            }
        }
    }

    fprintf(f, "\n};\n");

    if (asString) {
        fprintf(f, "\nsize_t NH_WEBIDL_FRAGMENT_FUNCTION_NAMES_PP_COUNT = sizeof(NH_WEBIDL_FRAGMENT_FUNCTION_NAMES_PP) / sizeof(NH_WEBIDL_FRAGMENT_FUNCTION_NAMES_PP[0]);\n");
    }
    else {
        fprintf(f, "\nsize_t NH_WEBIDL_FRAGMENT_FUNCTIONS_PP_COUNT = sizeof(NH_WEBIDL_FRAGMENT_FUNCTIONS_PP) / sizeof(NH_WEBIDL_FRAGMENT_FUNCTIONS_PP[0]);\n");
    }

NH_WEBIDL_DIAGNOSTIC_END(NH_WEBIDL_SUCCESS)
}

static NH_WEBIDL_RESULT Nh_WebIDL_createBindData(
    char *runtimePath_p, NH_WEBIDL_BINDING binding)
{
NH_WEBIDL_BEGIN()

    char filepath_p[1024] = {'\0'};
    sprintf(filepath_p, "%s/FragmentData.c", runtimePath_p);

    FILE *f = fopen(filepath_p, "w");
    if (f == NULL)
    {
        printf("Error opening file!\n");
        exit(1);
    }

    fprintf(f, "// LICENSE NOTICE ==================================================================================\n\n");
    fprintf(f, NH_LICENSE_NOTICE);

    Nh_WebIDL_createIncludes(f);
    Nh_WebIDL_createFragmentNames(f, NH_TRUE);
    Nh_WebIDL_createFragmentNames(f, NH_FALSE);
    Nh_WebIDL_createFragmentFunctions(f, runtimePath_p, NH_TRUE, binding);
    Nh_WebIDL_createFragmentFunctions(f, runtimePath_p, NH_FALSE, binding);

    fclose(f);

NH_WEBIDL_DIAGNOSTIC_END(NH_WEBIDL_SUCCESS)
}

// HEADER ===========================================================================================

static NH_WEBIDL_RESULT Nh_WebIDL_openHeaderFile1(
    FILE **File_pp, char *fragmentName_p, char *outdir_p, NH_WEBIDL_BINDING binding)
{
NH_WEBIDL_BEGIN()

    char *shortName_p = NULL;
    for (int i = 0; i < strlen(fragmentName_p); ++i) {
        if (fragmentName_p[i] == '_') {shortName_p = &fragmentName_p[i + 1]; break;}
    }
    NH_WEBIDL_CHECK_NULL(shortName_p)

    char outfilepath_p[1024] = {'\0'};
    sprintf(outfilepath_p, "%s/%s.idl.h", outdir_p, shortName_p);

    *File_pp = fopen(outfilepath_p, "w");
    NH_WEBIDL_CHECK_NULL(*File_pp)

    char fragmentNameUpper_p[1024] = {'\0'};
    for (int i = 0; i < strlen(fragmentName_p); ++i) {
        fragmentNameUpper_p[i] = toupper(fragmentName_p[i]);
    }

    switch (binding) {
        case NH_WEBIDL_BINDING_ECMASCRIPT :
            fprintf(*File_pp,"#ifndef NH_ECMASCRIPT_%s_H\n#define NH_ECMASCRIPT_%s_H\n\n", fragmentNameUpper_p, fragmentNameUpper_p);
            break;
    }

    fprintf(*File_pp,"#ifndef DOXYGEN_SHOULD_SKIP_THIS\n\n");
    fprintf(*File_pp, NH_LICENSE_NOTICE);
    fprintf(*File_pp,"#endif\n\n");

NH_WEBIDL_DIAGNOSTIC_END(NH_WEBIDL_SUCCESS)
}

static NH_WEBIDL_RESULT Nh_WebIDL_openHeaderFile2(
    FILE **File_pp, char *fragmentName_p, char *filepath_p, NH_WEBIDL_BINDING binding)
{
NH_WEBIDL_BEGIN()

    char outfilepath_p[1024] = {'\0'};
    sprintf(outfilepath_p, "%s.h", filepath_p);

    *File_pp = fopen(outfilepath_p, "w");
    NH_WEBIDL_CHECK_NULL(*File_pp)

    char fragmentNameUpper_p[1024] = {'\0'};
    for (int i = 0; i < strlen(fragmentName_p); ++i) {
        fragmentNameUpper_p[i] = toupper(fragmentName_p[i]);
    }

    fprintf(*File_pp,"#ifndef NH_WEBIDL_%s_H\n#define NH_WEBIDL_%s_H\n\n", fragmentNameUpper_p, fragmentNameUpper_p);
    fprintf(*File_pp,"#ifndef DOXYGEN_SHOULD_SKIP_THIS\n\n");
    fprintf(*File_pp, NH_LICENSE_NOTICE);
    fprintf(*File_pp,"#endif\n\n");

NH_WEBIDL_DIAGNOSTIC_END(NH_WEBIDL_SUCCESS)
}

static NH_WEBIDL_RESULT Nh_WebIDL_hexDumpToHeaderFile(
    FILE *File_p, Nh_WebIDL_SerializationBuffer *Buffer_p, char *fragmentName_p, NH_WEBIDL_BINDING binding)
{
NH_WEBIDL_BEGIN()

    char name_p[1024] = {'\0'};
    sprintf(name_p, "Nh_WebIDL_%s", fragmentName_p);

    fprintf(File_p,"/** @addtogroup WebIDLData Data\n *  \\ingroup WebIDL\n *  @{\n */\n\n");
    fprintf(File_p, "    unsigned char %s_p[] = {\n", name_p);

    int count = 0, totalCount = 0;
    for (int i = 0; i <= Buffer_p->index; ++i)
    {
        count = 0;
        for (int j = 0; j <= Buffer_p->maxSize; ++j) 
        {
            if (Buffer_p->index == i && (Buffer_p->maxSize - Buffer_p->size) == j) {break;}
            if (count == 0) {fprintf(File_p, "        ");}
            fprintf(
                File_p, 
                Buffer_p->index == i && (Buffer_p->maxSize - Buffer_p->size) == (j + 1) ? "0x%.2x" : "0x%.2x, ", 
                Buffer_p->array_pp[i][j] & 0xff
            );
            if (++count == 12) {fprintf(File_p, "\n"); count = 0;}
            totalCount++;
        }
    } 

    fprintf(File_p, count == 0 ? "    };\n\n" : "\n    };\n\n");
    fprintf(File_p, "    unsigned int %s_len = %d;\n", name_p, totalCount);

NH_WEBIDL_END(NH_WEBIDL_SUCCESS)
}

static NH_WEBIDL_RESULT Nh_WebIDL_declarationsToHeaderFile(
    FILE *File_p, char *fragmentName_p, Nh_WebIDL_Fragment Fragment, NH_WEBIDL_BINDING binding)
{
NH_WEBIDL_BEGIN()

    switch (binding) 
    {
        case NH_WEBIDL_BINDING_ECMASCRIPT :
            fprintf(File_p,"/** @addtogroup ECMAScriptFunctions Functions\n *  \\ingroup ECMAScript\n *  @{\n */\n");
            break;
        default :
            NH_WEBIDL_DIAGNOSTIC_END(NH_WEBIDL_ERROR_BAD_STATE)
    }

    for (int i = 0; i < Fragment.definitionCount; i++) 
    {
        Nh_WebIDL_Definition Definition = Fragment.Definitions_p[i];
    
        switch (Definition.type)
        {
            case NH_WEBIDL_DEFINITION_CALLBACK           : break; 
            case NH_WEBIDL_DEFINITION_CALLBACK_INTERFACE : break;
            case NH_WEBIDL_DEFINITION_INTERFACE          : 
            {
               Nh_WebIDL_Interface *Interface_p = Definition.data_p;

               for (int j = 0; j < Interface_p->Operations.length; ++j) 
               {
                   Nh_WebIDL_Operation *Operation_p = &((Nh_WebIDL_Operation*)Interface_p->Operations.bytes_p)[j];
                   char result_p[255] = {'\0'};
                   Nh_WebIDL_stringifyOperationResult(Operation_p, result_p);

                   switch (binding) 
                   {
                       case NH_WEBIDL_BINDING_ECMASCRIPT :
                           fprintf(
                               File_p, 
                               "\n    %s Nh_%s_%s(\n        Nh_ECMAScript_Object *This_p, Nh_List Arguments\n    );\n", 
                               result_p, fragmentName_p, Operation_p->name_p
                           );
                           break;
                       default :
                           NH_WEBIDL_DIAGNOSTIC_END(NH_WEBIDL_ERROR_BAD_STATE)
                   }
               }
                break;
            }
            case NH_WEBIDL_DEFINITION_INTERFACE_MIXIN    : break; 
            case NH_WEBIDL_DEFINITION_MIXIN              : break;
            case NH_WEBIDL_DEFINITION_NAMESPACE          : break;
            case NH_WEBIDL_DEFINITION_PARTIAL            : break;
            case NH_WEBIDL_DEFINITION_DICTIONARY         : break; 
            case NH_WEBIDL_DEFINITION_ENUM               : break;
            case NH_WEBIDL_DEFINITION_TYPEDEF            : break;
            case NH_WEBIDL_DEFINITION_INCLUDES_STATEMENT : break;
        }    
    }

NH_WEBIDL_DIAGNOSTIC_END(NH_WEBIDL_SUCCESS)
}

static NH_WEBIDL_RESULT Nh_WebIDL_closeHeaderFile(
    FILE *File_p)
{
NH_WEBIDL_BEGIN()

    fprintf(File_p,"\n/** @} */\n\n#endif");
    fclose(File_p);

NH_WEBIDL_DIAGNOSTIC_END(NH_WEBIDL_SUCCESS)
}

// GENERATE ========================================================================================

static void (*serializationCallback_f)(char *message_p) = NULL;
static NH_WEBIDL_BINDING genBinding;

NH_WEBIDL_RESULT Nh_WebIDL_beginGenerator(
    void (*callback_f)(char *message_p), NH_WEBIDL_BINDING binding)
{
NH_WEBIDL_BEGIN()

    serializationCallback_f = callback_f;
    genBinding = binding;

NH_WEBIDL_DIAGNOSTIC_END(NH_WEBIDL_SUCCESS)
}

NH_WEBIDL_RESULT Nh_WebIDL_generate(
    char *outdir_p, char *filepath_p)
{
NH_WEBIDL_BEGIN()

    Nh_WebIDL_SerializationData Data = Nh_WebIDL_serialize(filepath_p, serializationCallback_f);

    FILE *File_p;
    char fragmentName_p[1024] = {'\0'};
    Nh_WebIDL_getFragmentName(filepath_p, fragmentName_p);

    NH_WEBIDL_CHECK(Nh_WebIDL_openHeaderFile1(&File_p, fragmentName_p, outdir_p, genBinding))
    NH_WEBIDL_CHECK(Nh_WebIDL_declarationsToHeaderFile(File_p, fragmentName_p, Data.Fragment, genBinding))
    NH_WEBIDL_CHECK(Nh_WebIDL_closeHeaderFile(File_p))

    NH_WEBIDL_CHECK(Nh_WebIDL_openHeaderFile2(&File_p, fragmentName_p, filepath_p, genBinding))
    NH_WEBIDL_CHECK(Nh_WebIDL_hexDumpToHeaderFile(File_p, &Data.Buffer, fragmentName_p, genBinding))
    NH_WEBIDL_CHECK(Nh_WebIDL_closeHeaderFile(File_p))

    files_pp[fileCount] = malloc(sizeof(char) * (strlen(filepath_p) + 1));
    NH_WEBIDL_CHECK_MEM(files_pp[fileCount])

    strcpy(files_pp[fileCount++], filepath_p);
    SerializationData_p[serializationDataCount++] = Data;

NH_WEBIDL_DIAGNOSTIC_END(NH_WEBIDL_SUCCESS)
}

NH_WEBIDL_RESULT Nh_WebIDL_endGenerator(
    char *runtimepath_p)
{
NH_WEBIDL_BEGIN()

    Nh_WebIDL_createBindData(runtimepath_p, genBinding);

    for (int i = 0; i < serializationDataCount; ++i) {
        Nh_WebIDL_freeSerializationData(SerializationData_p[i]);
    } 
    serializationDataCount = 0;

    for (int i = 0; i < fileCount; ++i) {
        free(files_pp[i]);
        files_pp[i] = NULL;
    } 
    fileCount = 0;

    serializationCallback_f = NULL;

NH_WEBIDL_DIAGNOSTIC_END(NH_WEBIDL_SUCCESS)
}

